# =================================================================================================
# cardSync.conf
#
#    Copyright (C) 2025  Andrew Dixon
#    This program comes with ABSOLUTELY NO WARRANTY;
#    This is free software, and you are welcome to redistribute it under certain conditions;
#    See LICENSE file for details.
#
# Configuration file for cardSync.sh
#
# Each section defines sync rules for different data types (roms, saves, media, etc).
# Use '?' as a placeholder which will be replaced by each system name from [consoles].
# Set sync=true/false to enable or disable syncing for that section.
#
# Relatitve pathing can be used if the script resies on drive. For example, if the script and
# this configuration file reside on the card for the device in the root directory, you may
# forego absolute pathing. EX: /Volumes/sdcard/
#
# Exclusion list paths should be a path to the file ot be used. Can be global or system specific
# if the exclusion list file exists within specific directories. Exclusion lists are assumed to
# be at the destination location if a placeholder (?) is provided.
# =================================================================================================


# Roms -
## If exclusion lists are dropped into the root of the roms folder named [destination]-exlist
## The name replacement will build the filename with destination dir name in front. They can
## also be placed within the individual rom directory and the path updated to /roms/?/exlist.
[roms]
source=/source/rom/path/?
dest=roms/?
exlist=roms/?-exlist

# Save Games -
## Assumes that saves for retroarch (or other emulator) are formatted to save consistently,
## and that saves are stored by content directory. If not, you may need to adjust the paths.
[saves]
sync=true
source=/source/save/path/for/retroarch/saves/?
dest=saves/?

# Save States -
## Assumes that save states for retroarch (or other emulator) are formatted to save consistently,
## and that saves are stored by content directory. If not, you may need to adjust the paths.
[states]
sync=false
source=/source/save/path/for/retroarch/states/?
dest=states/?

# Gamelists -
## If you need to copy in gamelists from another location.
## EX: ES-DE gamelists into other EmulationStation installs.
[gamelists]
sync=true
source=gamelists/?
dest=roms/?

# Scraped Game Media -
## Copy media from another scraped environment. If gamelist.xml files are populated with relatitive
## paths, you can copy directly from the ES-DE folder structure, or just an individual folder for
## systems that link by name matching.
[media]
sync=true
source=/source/save/path/for/ES-DE/downloaded_media/?/covers
dest=roms/?/images

[consoles]
atarilynx lynx
fbneo fbneo
dreamcast dreamcast
gamegear gamegear
gb gb
gbc gbc
gba gba
genesis megadrive
mame mame
n64 n64
neogeo neogeo
neogeocd neogeocd
nes nes
psp psp
psx psx
saturn saturn
sega32x sega32x
segacd segacd
snes snes
tg16 pcengine
tg-cd pcenginecd
# End of file
