# =================================================================================================
# cardSync.conf
#
#    Copyright (C) 2025  Andrew Dixon
#    This program comes with ABSOLUTELY NO WARRANTY;
#    This is free software, and you are welcome to redistribute it under certain conditions;
#    See LICENSE file for details.
#
# Configuration file for cardSync.sh
#
# Each section defines sync rules for different data types (roms, saves, media, etc).
# Use '?' as a placeholder which will be replaced by each system name from [consoles].
# Set sync=true/false to enable or disable syncing for that section.
#
# Relatitve pathing can be used if the script resies on drive. For example, if the script and
# this configuration file reside on the card for the device in the root directory, you may
# forego absolute pathing. EX: /Volumes/sdcard/
#
# Exclusion list paths should be a path to the file ot be used. Can be global or system specific
# if the exclusion list file exists within specific directories. Exclusion lists are assumed to
# be at the destination location if a placeholder (?) is provided.
# =================================================================================================

[roms]
source=/Volumes/emuMaster/Games/?
dest=roms/?
# exlist=/path/to/exclusion/list

[saves]
sync=true
source=/Volumes/emuMaster/RoamData/retroarch/saves/?
dest=roms/saves/?

[states]
sync=false
source=/Volumes/emuMaster/RoamData/retroarch/states/?
dest=roms/savestates/?

[gamelists]
sync=true
source=gamelists/?
dest=roms/?

[media]
sync=true
source=/Volumes/emuMaster/RoamData/ES-DE/downloaded_media/?
dest=roms/?/images

[consoles]
arcade arcade
atarilynx atarilynx
fbneo fbneo
gb gb
gbc gbc
gba gba
genesis genesis
mame mame
nes nes
psx psx
sega32x sega32x
segacd segacd
snes snes
# End of file
