# =================================================================================================
# cardSync.conf
#
#    Copyright (C) 2025  Andrew Dixon
#    This program comes with ABSOLUTELY NO WARRANTY;
#    This is free software, and you are welcome to redistribute it under certain conditions;
#    See LICENSE file for details.
#
# Configuration file for cardSync.sh
#
# Each section defines sync rules for different data types (roms, saves, media, etc).
# Use '?' as a placeholder which will be replaced by each system name from [consoles].
# Set sync=true/false to enable or disable syncing for that section.
#
# Relatitve pathing can be used if the script resies on drive. For example, if the script and
# this configuration file reside on the card for the device in the root directory, you may
# forego absolute pathing. EX: /Volumes/sdcard/
#
# Exclusion list paths should be a path to the file ot be used. Can be global or system specific
# if the exclusion list file exists within specific directories. Exclusion lists are assumed to
# be at the destination location if a placeholder (?) is provided.
# =================================================================================================


# Roms -
## If exclusion lists are dropped into the root of the roms folder named [destination]-exlist
## The name replacement will build the filename with destination dir name in front. They can
## also be placed within the individual rom directory and the path updated to /roms/?/exlist.
[roms]
source=/source/rom/path/?
dest=Roms/?
exlist=roms/?-exlist

# Save Games -
## Assumes that saves for retroarch (or other emulator) are formatted to save consistently,
## and that saves are stored by content directory. If not, you may need to adjust the paths.
[saves]
sync=true
source=/source/save/path/for/retroarch/saves/?
dest=saves_RA/?

# Save States -
## Assumes that save states for retroarch (or other emulator) are formatted to save consistently,
## and that saves are stored by content directory. If not, you may need to adjust the paths.
[states]
sync=true
source=/source/save/path/for/retroarch/states/?
dest=states_RA/?

# Gamelists -
## If you need to copy in gamelists from another location.
## EX: ES-DE gamelists into other EmulationStation installs.
[gamelists]
sync=false
source=gamelists/?
dest=roms/?

# Scraped Game Media -
## Copy media from another scraped environment. If gamelist.xml files are populated with relatitive
## paths, you can copy directly from the ES-DE folder structure, or just an individual folder for
## systems that link by name matching.
[media]
sync=true
source=/Volumes/emuMaster/RoamData/ES-DE/downloaded_media/?/covers
dest=roms/?/Imgs

# List of Systems to sync.
## List is named as [source] [destination].
## This list is what gets repalced in the paths listed above for [source] and [destination]
[consoles]
arcade VARCADE
atomiswave ATOMISWAVE
cps1 CPS1
cps2 CPS2
cps3 CPS3
dreamcast DREAMCAST
fbneo FBNEO
gamegear GG
gb GB
gba GBA
gbc GBC
genesis MD
mame MAME
msx MSX
n64 N64
naomi NAOMI
neogeo NEOGEO
nes FC
ngpc NGPC
psp PSP
psx PS
sega32x SEGA32X
segacd MDCD
snes SFC
tg-cd PCECD
tg16 PCE
virtualboy VB
wonderswan WS
# End of file